import { defineField, defineType } from "sanity";

export const surftrip = defineType({
  name: "surftrip",
  title: "Surftrip",
  type: "document",
  fields: [
    defineField({
      name: "title",
      title: "Title",
      type: "string",
      validation: (rule) => rule.required().max(100),
    }),
    defineField({
      name: "slug",
      title: "Slug",
      type: "slug",
      options: { source: "title", maxLength: 96 },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "country",
      title: "Country",
      type: "string",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "level",
      title: "Level",
      type: "string",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "startDate",
      title: "Start Date",
      type: "date",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "endDate",
      title: "End Date",
      type: "date",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "shortDescription",
      title: "Short Description",
      type: "text",
      rows: 3,
      validation: (rule) => rule.required().max(320),
    }),
    defineField({
      name: "groupSize",
      title: "Group Size",
      type: "string",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "hospedaje",
      title: "Hospedaje",
      type: "string",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "duracion",
      title: "Duración",
      type: "string",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "aeropuerto",
      title: "Aeropuerto",
      type: "string",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "cardImage",
      title: "Card Image",
      type: "image",
      options: { hotspot: true },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "heroImage",
      title: "Hero Image",
      type: "image",
      options: { hotspot: true },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "heroKicker",
      title: "Hero Kicker",
      type: "string",
      initialValue: "SURFTRIP",
    }),
    defineField({
      name: "heroSubtitle",
      title: "Hero Subtitle",
      type: "text",
      rows: 3,
      validation: (rule) => rule.required().max(220),
    }),
    defineField({
      name: "heroTitleSuffix",
      title: "Hero Title Suffix",
      type: "string",
      description: "Optional collaborator or subtitle shown inline with the trip title, e.g. x Miguel Tudela.",
    }),
    defineField({
      name: "heroLongDescription",
      title: "Hero Long Description",
      type: "text",
      rows: 5,
      description: "Longer introductory copy for the first editorial summary section.",
    }),
    defineField({
      name: "heroLocationLabel",
      title: "Hero Location Label",
      type: "string",
      description: "Optional short location label shown above the trip summary.",
    }),
    defineField({
      name: "groupSizeLabel",
      title: "Group Size Label",
      type: "string",
      description: "Optional override for how group size should appear in the summary.",
    }),
    defineField({
      name: "videoSection",
      title: "Video Section",
      type: "surftripVideoSection",
    }),
    defineField({
      name: "dayInTripSection",
      title: "Day In Trip Section",
      type: "surftripDaySection",
    }),
    defineField({
      name: "waveTitle",
      title: "Wave Section Title",
      type: "string",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "waveBody",
      title: "Wave Section Body",
      type: "text",
      rows: 6,
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "waveImage",
      title: "Wave Section Image",
      type: "image",
      options: { hotspot: true },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "hotelTitle",
      title: "Hotel Section Title",
      type: "string",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "hotelBody",
      title: "Hotel Section Body",
      type: "text",
      rows: 6,
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "hotelImage",
      title: "Hotel Section Image",
      type: "image",
      options: { hotspot: true },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "waveSection",
      title: "Wave Section",
      type: "surftripFeatureSection",
      description: "Structured replacement for the legacy wave title/body/image fields.",
    }),
    defineField({
      name: "hotelSection",
      title: "Hotel Section",
      type: "surftripFeatureSection",
      description: "Structured replacement for the legacy hotel title/body/image fields.",
    }),
    defineField({
      name: "itineraryTitle",
      title: "Itinerary Section Title",
      type: "string",
      initialValue: "Como se vive este surftrip",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "itineraryBody",
      title: "Itinerary Section Body",
      type: "text",
      rows: 6,
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "primaryCtaLabel",
      title: "Primary CTA Label",
      type: "string",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "primaryCtaHref",
      title: "Primary CTA Link",
      type: "string",
      validation: (rule) => rule.required(),
      description: "Use internal paths or anchor links like #reserva",
    }),
    defineField({
      name: "experienceSections",
      title: "Experience Sections",
      type: "array",
      of: [{ type: "surftripFeatureSection" }],
      description: "Repeatable sections for yoga, videoanalisis, recovery, and other trip experiences.",
    }),
    defineField({
      name: "packageSection",
      title: "Package Section",
      type: "surftripPackageSection",
    }),
    defineField({
      name: "additionalInfoSection",
      title: "Additional Info Section",
      type: "surftripAdditionalInfoSection",
    }),
    defineField({
      name: "faqItems",
      title: "FAQ Items",
      type: "array",
      of: [{ type: "surftripFaqItem" }],
    }),
    defineField({
      name: "available",
      title: "Available Spots",
      type: "number",
      initialValue: 8,
      validation: (rule) => rule.required().min(0),
    }),
    defineField({
      name: "capacity",
      title: "Total Capacity",
      type: "number",
      initialValue: 12,
      validation: (rule) => rule.required().min(1),
    }),
    defineField({
      name: "featured",
      title: "Featured",
      type: "boolean",
      initialValue: false,
    }),
  ],
  preview: {
    select: {
      title: "title",
      subtitle: "country",
      media: "cardImage",
      available: "available",
      capacity: "capacity",
    },
    prepare({ title, subtitle, media, available, capacity }) {
      return {
        title,
        subtitle: `${subtitle || "No country"} - ${available ?? 0}/${capacity ?? 0} cupos`,
        media,
      };
    },
  },
});
